### ISSUE TITLE
MLJ Interface is not working anymore

### ISSUE THREAD

**Issue by rubsc** [sylvaticus/BetaML.jl#70]
The code

modelType = @load RandomForestClassifier pkg = "BetaML" verbosity=1
mod = modelType(
  n_trees = 2, 
  max_depth = 10
)

is not working in the latest version of BetaML.

**Comment by sylvaticus** [comment]
going to check, thanks to report....

**Comment by sylvaticus** [comment]
Hello, do you still have the issue after updating to latest versions?

**Comment by JoshuaBillson** [comment]
I found this issue because I was having a similar problem. Attempting to load the `RandomForestClassifier` model directly was failing to resolve, but doing so with `@load` worked. On further analysis, it appears that `RandomForestClassifier` is in the sub-module `Bmlj`, which needs to be explicitly included. For example:

```julia
# This Works
model = (MLJ.@load RandomForestClassifier pkg = "BetaML")()

# Also Works
model = BetaML.Bmlj.RandomForestClassifier()

# Doesn't Work
model = BetaML.RandomForestClassifier()
```

Moreover, the links to the MLJ models appear to be broken in the README.

I'm assuming this is a recent change? It would be nice to be able to access the `MLJ` models directly from the `BetaML` module. Alternatively, the documentation should be clearer to avoid confusion.

**Comment by sylvaticus** [comment]
Hi, `model = BetaML.RandomForestClassifier()` is NOT supposed to work.
You can access `RandomForestClassifier` and `RandomForestRegressor` trought the MLJ `@load` method, or the `RandomForestEstimator` trought the BetaML interface (the first two are just wrappers to the third one).
While names are different in this case, sometimes the names of the models are the same, this is why BetaML does NOT export the MLJ-interface models.
If you want the MLJ interface models without using `@load`, you can do:

```
using BetaML # or import
m = BetaML.Bmlj.RandomForestClassifier()
```

Thanks for the report on the links and let me know if I can close this issue...

**Comment by sylvaticus** [comment]
..closing... feel free to reopen if needed...
